### ISSUE TITLE
License for style guide boilerplate?

### ISSUE THREAD

**Issue by briannelson** [jeromecoupe/jekyllstyleguide#3]
Hi Jerome, this is a great-looking library. Does a certain license apply? Thanks for your help.

**Comment by jeromecoupe** [comment]
Free to use! Glad you find it helpful. A mention is always appreciated, though

Jérôme Coupé (mobile)

**Comment by briannelson** [comment]
Absolutely Jérôme. I don't want to demand too much of your time, but would it be possible to drop a license file in the repo? I'd be willing to submit a PR if that makes things easier.

**Comment by jeromecoupe** [comment]
On the road right now. Will do on friday night when I get home. It will be MIT.

Jérôme Coupé (mobile)

**Comment by briannelson** [comment]
That is awesome! Thanks a lot.
